### ISSUE TITLE
SSL not working on docker container

### ISSUE THREAD

**Issue by RandomBrown** [timmo001/home-panel#653]
I run HomePanel in Docker, in a Raspberry Pi, but not as an HassIO Addon.
When start, I obtain this log:

> home-panel_1  | -----------------------------------------------------------
home-panel_1  | Home Panel
home-panel_1  | -----------------------------------------------------------
home-panel_1  | [cont-init.d] 00-banner.sh: exited 0.
home-panel_1  | [cont-init.d] secrets.sh: executing...
home-panel_1  | /var/run/s6/etc/cont-init.d/secrets.sh: line 7: bashio::fs.file_exists: command not found
home-panel_1  | /var/run/s6/etc/cont-init.d/secrets.sh: line 8: bashio::log.info: command not found
home-panel_1  | sed: bad option in substitution expression
home-panel_1  | [cont-init.d] secrets.sh: exited 0.
home-panel_1  | [cont-init.d] done.
home-panel_1  | [services.d] starting services
home-panel_1  | Run Home Panel..
home-panel_1  | [services.d] done.
home-panel_1  | info: Feathers application started on http://localhost:8234

Note the errors in lines 7 and 8. 
Is that why it doesn't work on HTTPS?

**Comment by timmo001** [comment]
Please update. Your version has errors that have been fixed

**Comment by RandomBrown** [comment]
It's update:

> $ docker pull timmo001/home-panel
Using default tag: latest
latest: Pulling from timmo001/home-panel
Digest: sha256:2e3184ce6e4cf4eaa223476e3b91cedb251d3f27b195d30a9248df0775afb6c8
Status: Image is up to date for timmo001/home-panel:latest
docker.io/timmo001/home-panel:latest

The SO is Raspbian (update & upgrade):

> $ uname -a
Linux 2domo 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux

>  $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by timmo001** [comment]
You must be on an old container version since your logs contain these errors where the lines have been replaced.

> home-panel_1 | /var/run/s6/etc/cont-init.d/secrets.sh: line 7: bashio::fs.file_exists: command not found
> home-panel_1 | /var/run/s6/etc/cont-init.d/secrets.sh: line 8: bashio::log.info: command not found

**Comment by RandomBrown** [comment]
You are totally right. My mistake was that I updated the image, but I did not update the container with the new image.
But SSL still does not work:

> home-panel_1  | -----------------------------------------------------------
home-panel_1  | Home Panel
home-panel_1  | -----------------------------------------------------------
home-panel_1  | [cont-init.d] 00-banner.sh: exited 0.
home-panel_1  | [cont-init.d] secrets.sh: executing...
home-panel_1  | [cont-init.d] secrets.sh: exited 0.
home-panel_1  | [cont-init.d] done.
home-panel_1  | [services.d] starting services
home-panel_1  | Run Home Panel..
home-panel_1  | [services.d] done.
home-panel_1  | info: Feathers application started on http://localhost:8234

I use this file to create the container (docker-compose.yml):

> version: '3'
services:
  home-panel:
    image: timmo001/home-panel
    environment:
      SSL_CERTFILE: cert.pem
      SSL_KEYFILE: privkey.pem
    ports:
      - 8234:8234
    volumes:
      - home_panel_data:/data
      - /home/pi/ssl/cert.pem:/data/ssl/cert.pem
      - /home/pi/ssl/privkey.pem:/data/ssl/privkey.pem
volumes:
  home_panel_data: {}

And I can see these certificate files on the container:

> $ docker exec -it home-panel_home-panel_1 /bin/bash
root@e1a29a9dd4a5:/$ ls -la /data/ssl/
total 16
drwxr-xr-x    2 root     root          4096 Sep 23 19:06 .
drwxr-xr-x    4 root     root          4096 Oct 12 17:34 ..
-rw-r--r--    1 root     root          1915 Sep 23 19:03 cert.pem
-rw-r--r--    1 root     root          1708 Sep 22 18:29 privkey.pem
root@e1a29a9dd4a5:/$

**Comment by timmo001** [comment]
The upgrade of the API caused the SSL logic to be lost. This is fixed now and will be in the next release
